version: '3.3'

services:
  backend:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - RUN_MIGRATIONS=1
    command: bash -c "python ./hotel/manage.py migrate && python ./hotel/manage.py migrate && python ./hotel/manage.py runserver 0.0.0.0:8000"

  frontend:
    restart: always
    build: ./front
    depends_on:
      - backend


    ports:
        - "3000:3000"


  db:
    image: postgres:latest
    container_name: db
    volumes:
      - pgdbdata:/var/lib/postgresql/prod/data/

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - backend

    ports:
      - "5432:5432"

volumes:
  pgdbdata: