# Generated by Django 4.2.5 on 2023-09-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxe',
            name='persons',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='luxeplus',
            name='persons',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='luxepremium',
            name='persons',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='standard',
            name='persons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='booked',
            field=models.ManyToManyField(blank=True, to='hotel.bookingdate'),
        ),
    ]
