# Generated by Django 4.2.5 on 2023-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_bookingdate_first_name_bookingdate_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
