# Generated by Django 4.2.5 on 2023-09-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_bookingdate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdate',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='free_rooms',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingdate',
            name='type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
