# Generated by Django 4.2.5 on 2023-10-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_bookingdate_comment'),
        ('hotel', '0010_custom_add_data'),
    ]

    operations = [
    ]
