# Generated by Django 4.2.5 on 2023-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_bookingdate_amount_bookingdate_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
